export enum BatchStatus {
  ACTIVE = 'ACTIVE',
  EXPIRED = 'EXPIRED',
  EXHAUSTED = 'EXHAUSTED',
}

export enum StockMovementType {
  STOCK_IN = 'STOCK_IN',
  STOCK_OUT = 'STOCK_OUT',
  ADJUSTMENT = 'ADJUSTMENT',
  TRANSFER_IN = 'TRANSFER_IN',
  TRANSFER_OUT = 'TRANSFER_OUT',
  RETURN = 'RETURN',
  RETURN_IN = 'RETURN_IN',
  RETURN_OUT = 'RETURN_OUT',
  EXPIRED = 'EXPIRED',
  DAMAGED = 'DAMAGED',
}

export enum ExpiryStatus {
  EXPIRED = 'EXPIRED',
  EXPIRING_WITHIN_30_DAYS = 'EXPIRING_WITHIN_30_DAYS',
  EXPIRING_WITHIN_60_DAYS = 'EXPIRING_WITHIN_60_DAYS',
  SAFE = 'SAFE',
}

export enum StockHealth {
  LOW_STOCK = 'LOW_STOCK',
  OVERSTOCK = 'OVERSTOCK',
  FAST_MOVING = 'FAST_MOVING',
  SLOW_MOVING = 'SLOW_MOVING',
  DEAD_STOCK = 'DEAD_STOCK',
  NORMAL = 'NORMAL',
}
