import { OutboxRepository } from './outbox.repository';
import { OutboxService } from './outbox.service';
import { OutboxStatus, DomainEventEnvelope } from './types';
export { OutboxRepository, OutboxService, OutboxStatus };
export type { DomainEventEnvelope };
export declare const DomainEvents: {
    readonly PRESCRIPTION_SUBMITTED: "clinical.prescription.submitted";
    readonly ENCOUNTER_COMPLETED: "clinical.encounter.completed";
    readonly STOCK_RESERVATION_CREATED: "inventory.reservation.created";
    readonly STOCK_RESERVATION_FULFILLED: "inventory.reservation.fulfilled";
    readonly STOCK_BATCH_LOW: "inventory.batch.low";
    readonly INVOICE_ISSUED: "finance.invoice.issued";
    readonly INVOICE_PAID: "finance.invoice.paid";
    readonly CLAIM_SUBMITTED: "finance.claim.submitted";
    readonly CLAIM_ADJUDICATED: "finance.claim.adjudicated";
    readonly PATIENT_CREATED: "patient.created";
    readonly PATIENT_MERGED: "patient.merged";
    readonly WORKFLOW_INSTANCE_CREATED: "workflow.instance.created";
    readonly WORKFLOW_INSTANCE_APPROVAL_REQUESTED: "workflow.instance.approval_requested";
    readonly WORKFLOW_INSTANCE_APPROVED: "workflow.instance.approved";
    readonly WORKFLOW_INSTANCE_REJECTED: "workflow.instance.rejected";
    readonly WORKFLOW_INSTANCE_COMPLETED: "workflow.instance.completed";
    readonly WORKFLOW_INSTANCE_CANCELLED: "workflow.instance.cancelled";
    readonly WORKFLOW_DEFINITION_CREATED: "workflow.definition.created";
    readonly WORKFLOW_DEFINITION_UPDATED: "workflow.definition.updated";
    readonly MARKETPLACE_CART_CREATED: "marketplace.cart.created";
    readonly MARKETPLACE_CART_UPDATED: "marketplace.cart.updated";
    readonly MARKETPLACE_ORDER_CREATED: "marketplace.order.created";
    readonly MARKETPLACE_ORDER_CONFIRMED: "marketplace.order.confirmed";
    readonly MARKETPLACE_INVENTORY_RESERVED: "marketplace.inventory.reserved";
    readonly MARKETPLACE_PAYMENT_COMPLETED: "marketplace.payment.completed";
    readonly MARKETPLACE_DELIVERY_ASSIGNED: "marketplace.delivery.assigned";
    readonly MARKETPLACE_ORDER_COMPLETED: "marketplace.order.completed";
};
