export const COMPLIANCE_DATA_CLASSES = [
  'IDENTITY_PROFILE',
  'AUTHENTICATION_SECURITY',
  'PRIVACY_PREFERENCES',
  'CONSENT_EVIDENCE',
  'TENANT_MEMBERSHIP',
  'AUDIT_EVIDENCE',
  'PATIENT_PROFILE',
  'PATIENT_NOTIFICATION',
  'PATIENT_TIMELINE',
  'MEDICINE_RESERVATION',
  'INVENTORY_OPERATION',
  'BILLING_FINANCIAL',
] as const;

export const COMPLIANCE_PURPOSES = [
  'ACCOUNT_SECURITY',
  'SERVICE_DELIVERY',
  'INVENTORY_OPERATIONS',
  'BILLING_TAX',
  'PRIVACY_PREFERENCE',
  'LEGAL_COMPLIANCE',
  'AUDIT_SECURITY',
  'PATIENT_CARE',
] as const;

export const COMPLIANCE_DISPOSITIONS = ['RETAIN', 'DELETE', 'ANONYMIZE'] as const;
export const COMPLIANCE_EVALUATION_CONTEXTS = [
  'ACCESS',
  'SUBJECT_REQUEST',
  'RETENTION_EXPIRY',
] as const;
export const COMPLIANCE_LEGAL_HOLD_REASONS = [
  'LITIGATION',
  'REGULATORY_REQUEST',
  'SECURITY_INVESTIGATION',
  'CONTRACTUAL_PRESERVATION',
  'OTHER',
] as const;

export type ComplianceDataClass = (typeof COMPLIANCE_DATA_CLASSES)[number];
export type CompliancePurpose = (typeof COMPLIANCE_PURPOSES)[number];
export type ComplianceDisposition = (typeof COMPLIANCE_DISPOSITIONS)[number];
export type ComplianceEvaluationContext = (typeof COMPLIANCE_EVALUATION_CONTEXTS)[number];
export type ComplianceLegalHoldReason = (typeof COMPLIANCE_LEGAL_HOLD_REASONS)[number];

export const MAX_COMPLIANCE_EVIDENCE_PAGE_SIZE = 100;
