export enum EncounterStatus {
  PLANNED = 'PLANNED',
  IN_PROGRESS = 'IN_PROGRESS',
  ON_HOLD = 'ON_HOLD',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum EncounterType {
  AMBULATORY = 'AMBULATORY',
  EMERGENCY = 'EMERGENCY',
  INPATIENT = 'INPATIENT',
  TELEMEDICINE = 'TELEMEDICINE',
}

export enum PrescriptionStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  PARTIALLY_DISPENSED = 'PARTIALLY_DISPENSED',
  FULLY_DISPENSED = 'FULLY_DISPENSED',
  CANCELLED = 'CANCELLED',
}
