export enum MedicalRecordType {
  PRESCRIPTION = 'PRESCRIPTION',
  LAB_REPORT = 'LAB_REPORT',
  XRAY = 'XRAY',
  MRI = 'MRI',
  CT_SCAN = 'CT_SCAN',
  VACCINATION = 'VACCINATION',
  DISCHARGE_SUMMARY = 'DISCHARGE_SUMMARY',
  INSURANCE = 'INSURANCE',
  OTHER = 'OTHER',
}
